---
title: "Cover letter, Applied Epi"
date: "2022-11-24"
author: Matthieu ROLLAND 
format: html
---

[mj.rolland@gmail.com](mj.rolland@gmail.com)  
+ 33 6 31 73 31 33  

To whom it may concern,

I have a masters degree in biostatistics (2009), which I followed with a 2 year training to field epidemiology (the French FETP program, PROFET, 2009-2011) and I will be defending my thesis in statistics applied to epidemiology in 2023.

For the past 14 years I have worked in the field of statistics and data science applied to epidemiology, medical research and public health, both in France and in the USA (2012-2016).

I am a passionate R user, strong advocate of the *tidyverse* and I believe in the promotion of free open source tools for science in general and public health in particular. I am a great supporter of the Epi R Handbook initiative.

I have taught R to colleagues throughout my career. When I was working in Bordeaux’ public health school (Isped) I taught R and the tidyverse to members of the Alima NGO with whom I was sharing offices (`{ggplot2}`, `{dplyr}`, `{tidyr}`). I have given many R related talks with the R user group of Grenoble (FR) of which I am the coordinator (website and YouTube channel : [r-in-grenoble.github.io/sessions.html](r-in-grenoble.github.io/sessions.html)). I have taught several applied statistics classes at the Grenoble University for healthcare practitioners (nurses, doctors, etc), mainly linear and logistic regression.

I am the co-author of the Epidemiology CRAN task view ([cran.r-project.org/web/views/Epidemiology.html)](cran.r-project.org/web/views/Epidemiology.html)) and was a project manager for the R Epidemics Consortium (RECON) to develop their task manager ([tasks.repidemicsconsortium.org/](tasks.repidemicsconsortium.org/)).

I feel capable of undertaking your « general » R/epi modules and some of the more specific ones. I have extensive experience in data visualisation with `{ggplot2}`, reporting with `{rmarkdown}` and now `{quarto}`, working with Git and GitHub/GitLab, working with geo-spatial data and I use RedCap. However, I have little experience with `{shiny}` and I have never used SQL with R.

I speak French (mother tongue) and English (bilingual, my mother is British) and a little German. I am willing to travel internationally. I live in Grenoble (FR). Regarding availability, I am open to discussion but for 2023 I will probably be available for only one or two week-long courses plus a couple of half day courses each month. I am comfortable with teaching at a distance but I prefer working in-person, especially for teaching.

I am a sociable and patient person and I enjoy teaching, R and field epidemiology, and would be very interested in working with Applied Epi.  

I am available for any further question and hope to hear from you soon.

Kind regards,  
Matthieu
